const profanityPatterns = [
  "porra",
  "caralho",
  "merda",
  "puta",
  "puto",
  "foda",
  "fodase",
  "fode",
  "buceta",
  "cacete",
  "cu",
  "desgraca",
  "inferno",
  "idiota",
  "burro",
  "bosta",
  "shit",
  "fuck",
  "fucking",
  "damn",
  "bitch",
  "asshole",
  "bastard",
];

const topicSignals = [
  {
    label: "violencia",
    words: ["matar", "morte", "sangue", "arma", "tiro", "facada", "guerra", "briga", "violencia", "assassinato"],
    ageWeight: 3,
  },
  {
    label: "sexo ou nudez",
    words: ["sexo", "sexual", "nudez", "pelado", "pornografia", "erotico", "tesao"],
    ageWeight: 3,
  },
  {
    label: "drogas",
    words: ["droga", "maconha", "cocaina", "crack", "alcool", "bebida", "bebado", "fumar"],
    ageWeight: 2,
  },
  {
    label: "terror ou medo",
    words: ["terror", "assustador", "medo", "monstro", "assombrado", "susto", "horror"],
    ageWeight: 2,
  },
  {
    label: "jogos",
    words: ["game", "jogo", "jogar", "minecraft", "roblox", "fortnite", "gta", "console"],
    ageWeight: 0,
  },
  {
    label: "educacao",
    words: ["aula", "tutorial", "ensinar", "explicar", "historia", "matematica", "ciencia", "dica"],
    ageWeight: 0,
  },
  {
    label: "humor",
    words: ["piada", "engracado", "comedia", "meme", "zoeira", "risada"],
    ageWeight: 0,
  },
  {
    label: "noticias ou opiniao",
    words: ["noticia", "politica", "governo", "opiniao", "debate", "eleicao", "crime"],
    ageWeight: 1,
  },
];

function normalizeText(value) {
  return String(value || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase();
}

function parseVideoId(input) {
  let url;
  try {
    url = new URL(String(input || "").trim());
  } catch {
    return null;
  }

  if (url.hostname.includes("youtu.be")) return url.pathname.split("/").filter(Boolean)[0] || null;
  if (url.hostname.includes("youtube.com")) {
    if (url.pathname === "/watch") return url.searchParams.get("v");
    if (url.pathname.startsWith("/shorts/")) return url.pathname.split("/")[2] || null;
    if (url.pathname.startsWith("/embed/")) return url.pathname.split("/")[2] || null;
  }

  return null;
}

function extractBalancedJson(source, marker) {
  const markerIndex = source.indexOf(marker);
  if (markerIndex === -1) return null;

  const start = source.indexOf("{", markerIndex);
  if (start === -1) return null;

  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let i = start; i < source.length; i += 1) {
    const char = source[i];

    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === "\"") {
        inString = false;
      }
      continue;
    }

    if (char === "\"") inString = true;
    if (char === "{") depth += 1;
    if (char === "}") depth -= 1;
    if (depth === 0) return source.slice(start, i + 1);
  }

  return null;
}

async function fetchYoutubeMetadata(videoId) {
  const response = await fetch(`https://www.youtube.com/watch?v=${videoId}&hl=pt-BR`, {
    headers: {
      "Accept-Language": "pt-BR,pt;q=0.9,en;q=0.8",
      "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125 Safari/537.36",
    },
  });

  if (!response.ok) {
    throw new Error(`O YouTube respondeu com status ${response.status}.`);
  }

  const html = await response.text();
  const playerJson = extractBalancedJson(html, "ytInitialPlayerResponse");
  if (!playerJson) {
    throw new Error("Nao consegui localizar os metadados do player do YouTube.");
  }

  const player = JSON.parse(playerJson);
  const details = player.videoDetails || {};
  const tracks = player.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];

  return {
    title: details.title || "Video do YouTube",
    author: details.author || "Canal desconhecido",
    durationSeconds: Number(details.lengthSeconds || 0),
    thumbnail: `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`,
    tracks: tracks.map((track) => ({
      name: track.name?.simpleText || track.name?.runs?.map((run) => run.text).join("") || track.languageCode,
      languageCode: track.languageCode,
      baseUrl: track.baseUrl,
      isAutoGenerated: track.kind === "asr",
    })),
  };
}

async function fetchTranscript(tracks) {
  if (!tracks.length) {
    throw new Error("Este video nao possui legendas publicas acessiveis.");
  }

  const preferred =
    tracks.find((track) => track.languageCode?.startsWith("pt")) ||
    tracks.find((track) => track.languageCode?.startsWith("en")) ||
    tracks[0];

  const url = new URL(preferred.baseUrl);
  url.searchParams.set("fmt", "json3");

  const response = await fetch(url, {
    headers: {
      "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125 Safari/537.36",
    },
  });

  if (!response.ok) {
    throw new Error(`Nao consegui baixar a legenda selecionada (${response.status}).`);
  }

  const data = await response.json();
  const entries = [];

  for (const event of data.events || []) {
    const text = (event.segs || [])
      .map((seg) => seg.utf8 || "")
      .join("")
      .replace(/\s+/g, " ")
      .trim();

    if (text) entries.push({ startMs: event.tStartMs || 0, text });
  }

  if (!entries.length) {
    throw new Error("A legenda foi encontrada, mas veio sem texto util.");
  }

  return {
    track: preferred,
    entries,
    text: entries.map((entry) => entry.text).join(" ").replace(/\s+/g, " ").trim(),
  };
}

function countMatches(text, terms) {
  const normalized = normalizeText(text);
  return terms.reduce((total, term) => {
    const escaped = normalizeText(term).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const pattern = new RegExp(`\\b${escaped}\\b`, "g");
    const matches = normalized.match(pattern);
    return total + (matches ? matches.length : 0);
  }, 0);
}

function analyzeTranscript(transcript) {
  const normalized = normalizeText(transcript);
  const words = normalized.match(/\b[\w']+\b/g) || [];
  const profanity = profanityPatterns
    .map((term) => ({ term, count: countMatches(transcript, [term]) }))
    .filter((item) => item.count > 0)
    .sort((a, b) => b.count - a.count);

  const topics = topicSignals
    .map((topic) => ({
      label: topic.label,
      count: countMatches(transcript, topic.words),
      ageWeight: topic.ageWeight,
    }))
    .filter((topic) => topic.count > 0)
    .sort((a, b) => b.count - a.count);

  const profanityTotal = profanity.reduce((total, item) => total + item.count, 0);
  const sensitiveScore = topics.reduce((total, topic) => total + topic.count * topic.ageWeight, 0);
  const profanityDensity = words.length ? profanityTotal / words.length : 0;
  const hasEnoughWordsForDensity = words.length >= 100;

  let ageRating = "Livre";
  if (profanityTotal >= 20 || (hasEnoughWordsForDensity && profanityDensity > 0.025) || sensitiveScore >= 16) {
    ageRating = "18+";
  } else if (profanityTotal >= 10 || (hasEnoughWordsForDensity && profanityDensity > 0.014) || sensitiveScore >= 9) {
    ageRating = "16+";
  } else if (profanityTotal >= 4 || (hasEnoughWordsForDensity && profanityDensity > 0.006) || sensitiveScore >= 4) {
    ageRating = "14+";
  } else if (profanityTotal > 0 || sensitiveScore > 0) {
    ageRating = "12+";
  }

  const reasons = [];
  if (profanityTotal) reasons.push(`${profanityTotal} palavra(s) de baixo calao detectada(s)`);
  for (const topic of topics.slice(0, 3)) reasons.push(`mencoes relacionadas a ${topic.label}`);
  if (!reasons.length) reasons.push("nao foram encontrados sinais fortes de linguagem adulta na transcricao");

  const topTopic = topics[0]?.label || inferGenericTopic(normalized);

  return {
    ageRating,
    profanityTotal,
    profanity,
    topics,
    wordCount: words.length,
    summary: buildSummary(topTopic, topics, profanityTotal),
    reasons,
  };
}

function inferGenericTopic(text) {
  if (text.includes("obrigado") || text.includes("inscrev")) return "conteudo de canal ou apresentacao";
  return "assunto geral";
}

function buildSummary(topTopic, topics, profanityTotal) {
  const topicText = topics.length ? topics.slice(0, 3).map((topic) => topic.label).join(", ") : topTopic;
  const tone = profanityTotal > 0 ? "com linguagem informal ou forte" : "sem palavroes relevantes detectados";
  return `O video parece tratar de ${topicText}, ${tone}.`;
}

async function analyzeYoutubeUrl(url) {
  const videoId = parseVideoId(url);
  if (!videoId) {
    const error = new Error("Cole um link valido do YouTube.");
    error.statusCode = 400;
    throw error;
  }

  const metadata = await fetchYoutubeMetadata(videoId);
  const transcript = await fetchTranscript(metadata.tracks);
  const analysis = analyzeTranscript(transcript.text);

  return {
    videoId,
    metadata: {
      title: metadata.title,
      author: metadata.author,
      durationSeconds: metadata.durationSeconds,
      thumbnail: metadata.thumbnail,
    },
    captions: {
      languageCode: transcript.track.languageCode,
      name: transcript.track.name,
      isAutoGenerated: transcript.track.isAutoGenerated,
    },
    analysis,
    transcript: transcript.text,
    transcriptEntries: transcript.entries,
  };
}

function analyzeManualText(input) {
  const transcript = String(input || "").trim();

  if (transcript.length < 20) {
    const error = new Error("Cole uma transcricao com texto suficiente para analisar.");
    error.statusCode = 400;
    throw error;
  }

  return {
    metadata: {
      title: "Transcricao manual",
      author: "Texto colado",
      durationSeconds: 0,
      thumbnail: "/youtube-placeholder.svg",
    },
    captions: {
      languageCode: "manual",
      name: "Manual",
      isAutoGenerated: false,
    },
    analysis: analyzeTranscript(transcript),
    transcript,
    transcriptEntries: [],
  };
}

module.exports = {
  analyzeManualText,
  analyzeTranscript,
  analyzeYoutubeUrl,
  parseVideoId,
};
